---
title: "Intrusion Detection System"
author: "Ankit Shaw"
date: "September 16, 2017"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Load Data

```{r data, echo = TRUE}
library(caret)
data<-read.table("kddcup.data_10_percent_corrected.csv",sep = ",")
colnames(data) = c("duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes", 
                   "land", "wrong_fragment", "urgent", "hot", "num_failed_logins", "logged_in", 
                   "num_compromised", "root_shell", "su_attempted", "num_root", "num_file_creations", 
                   "num_shells", "num_access_files", "num_outbound_cmds", "is_hot_login",
                   "is_guest_login", "count", "srv_count", "serror_rate", "srv_serror_rate", 
                   "rerror_rate","srv_rerror_rate", "same_srv_rate", "diff_srv_rate",                 
                   "srv_diff_host_rate","dst_host_count","dst_host_srv_count",
                   "dst_host_same_srv_rate", "dst_host_diff_srv_rate",
                   "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate",
                   "dst_host_serror_rate","dst_host_srv_serror_rate", "dst_host_rerror_rate",
                   "dst_host_srv_rerror_rate", "result")
str(data)
```

## Pre Processing

```{r pre-processing, echo=TRUE}
#DOS: denial-of-service, e.g. syn flood;
#R2L: unauthorized access from a remote machine, e.g. guessing password;
#U2R:  unauthorized access to local superuser (root) privileges, e.g., various ``buffer overflow'' attacks;
#probing: surveillance and other probing, e.g., port scanning.

data$result = as.character(data$result)
data$result[data$result == "ipsweep."] = "probe"
data$result[data$result == "portsweep."] = "probe"
data$result[data$result == "nmap."] = "probe"
data$result[data$result == "satan."] = "probe"
data$result[data$result == "buffer_overflow."] = "u2r"
data$result[data$result == "loadmodule."] = "u2r"
data$result[data$result == "perl."] = "u2r"
data$result[data$result == "rootkit."] = "u2r"
data$result[data$result == "back."] = "dos"
data$result[data$result == "land."] = "dos"
data$result[data$result == "neptune."] = "dos"
data$result[data$result == "pod."] = "dos"
data$result[data$result == "smurf."] = "dos"
data$result[data$result == "teardrop."] = "dos"
data$result[data$result == "ftp_write."] = "r2l"
data$result[data$result == "guess_passwd."] = "r2l"
data$result[data$result == "imap."] = "r2l"
data$result[data$result == "multihop."] = "r2l"
data$result[data$result == "phf."] = "r2l"
data$result[data$result == "spy."] = "r2l"
data$result[data$result == "warezclient."] = "r2l"
data$result[data$result == "warezmaster."] = "r2l"
data$result[data$result == "normal."] = "normal"
data$result = as.factor(data$result)
```

## Correlation

```{r correlation, echo=TRUE}
library(corrplot)
data2 <- data[,5:41]
colnames(data2) <- NULL
correlation <- cor(data2)
corrplot(correlation, method="circle", na.label= '.')
```

## EDA

```{r eda1, echo=TRUE}
# Observation: dst_host_same_src_port_rate has slight effect on the intrusion type.
# for "dst_host_same_src_port_rate" value greater than equal to 1 it can be "probe" and "r2l""
qplot(dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,colour=result,data=data)
```

## EDA

```{r eda2, echo=TRUE}
# Observation: "flag" is a strong predictor. for flag= "REG" and "S0" it is "dos"
qplot(service,flag,colour=result,data=data)
```

## EDA

```{r eda3, echo=TRUE}
# Observation: For duration Greater than 30000 we can see it's 'probe'
# Therefore duration itself is a strong predictor
qplot(duration,src_bytes,colour=result,data=data)
```

## EDA

```{r eda4, echo=TRUE}
# Observation: For duration Greater than 30000 we can see it's 'probe'
# Observation: protocol-type "tcp" has "DOS" intrusion type. It is also a strong predictor of "dos" type.
qplot(service,protocol_type,colour=result,data=data)
```

## EDA

```{r eda5, echo=TRUE}
# Observation: No such clear identification
qplot(flag,land,colour=result,data=data)
```

## EDA

```{r eda6, echo=TRUE}
# Observation: For serror_rate and srv_serror_rate=0 or 1 its "dos" and
# serror_rate between 0.25 to 0.5 its "probe""
qplot(serror_rate,srv_serror_rate,colour=result,data=data)
```

## EDA

```{r eda7, echo=TRUE}
# Observation:For duration Greater than 30000 we can see it's 'probe'
qplot(duration,src_bytes,colour=result,data=data)
```

## EDA

```{r eda8, echo=TRUE}
# Result: We can clearly see flag is a strong predictor for "dos" type intrusion
A=table(data$flag,data$result)
round(prop.table(A)*100,1)
```





